baseURL = 'https://linux87s.github.io/'
languageCode = 'vi'
defaultContentLanguage = 'vi'
title = 'linux87s'
theme = 'PaperMod'
[pagination]
  pagerSize = 10

[params]
  env = 'production'
  author = 'linux87s'
  description = 'Tổng hợp các ghi chú của tôi.'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = 'Bài viết'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Thẻ'
    url = '/tags/'
    weight = 2
  [[menu.main]]
    name = 'Về tôi'
    url = '/about/'
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
